version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: intelligent-chat-mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

  qdrant:
    image: qdrant/qdrant:latest
    container_name: intelligent-chat-qdrant
    ports:
      - '6333:6333'
      - '6334:6334'
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  mongodb_data:
    name: intelligent-chat-mongodb-data
  qdrant_data:
    name: intelligent-chat-qdrant-data
